spring:
  profiles:
    active: stress
---
spring:
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db-init/schema.sql
  output:
    ansi:
      enabled: always
logging:
  level:
    me.snowlight: debug
    org.springframework.r2dbc.core: debug
---
spring:
  config:
    activate:
      on-profile: stress
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/sample
    username: user
    password: 1234
  sql:
    init:
      mode: never
logging:
  level:
    me.snowlight: debug
    org.springframework.r2dbc.core: off