version: "3.8"
services:
  webflux-reactor:
    container_name: webflux-reactor
    image: spring-webflux-reactor-article:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - spring.r2dbc.url=r2dbc:pool:mariadb://192.168.0.17:3306/sample